use crate::domain::decl_model::HtmlDeclMeta;

pub const TYPED_EXACT_DECL_COLUMNS: &[u32] = &[0u32, 1u32, 2u32, 3u32, 4u32, 5u32, 6u32, 7u32, 8u32, 9u32, 10u32, 11u32, 12u32, 13u32, 14u32, 15u32, 16u32, 17u32, 18u32, 19u32, 20u32, 21u32, 22u32, 23u32, 24u32, 25u32, 26u32, 27u32, 28u32, 29u32, 30u32, 31u32, 32u32, 33u32, 34u32, 35u32, 36u32, 37u32, 40u32, 41u32, 44u32, 49u32, 50u32, 56u32, 60u32, 61u32, 62u32, 63u32, 42u32, 43u32, 45u32, 46u32, 47u32, 48u32, 51u32, 52u32, 53u32, 54u32, 55u32, 57u32, 58u32, 59u32, 64u32, 65u32, 68u32, 69u32, 70u32, 71u32, 72u32, 73u32, 74u32, 75u32, 76u32, 77u32, 78u32, 79u32, 80u32, 81u32, 82u32, 83u32, 84u32, 86u32, 87u32, 88u32, 89u32, 90u32, 91u32, 92u32, 93u32, 94u32, 95u32, 96u32, 99u32, 100u32, 101u32, 102u32, 103u32, 104u32, 105u32, 106u32, 107u32, 108u32, 109u32, 112u32, 113u32, 114u32, 115u32, 116u32, 117u32, 118u32, 119u32, 120u32, 123u32, 124u32, 125u32, 126u32, 127u32, 128u32, 129u32, 130u32, 131u32, 132u32, 135u32, 136u32, 137u32, 138u32, 139u32, 140u32, 141u32, 142u32, 143u32, 144u32, 145u32, 146u32, 147u32, 148u32, 149u32, 150u32, 153u32, 154u32, 155u32, 156u32, 157u32, 158u32, 165u32, 166u32, 167u32, 168u32, 169u32, 170u32, 183u32, 188u32, 189u32, 190u32, 191u32, 196u32, 197u32, 198u32, 201u32, 202u32, 203u32, 204u32, 205u32, 207u32, 208u32, 209u32, 210u32, 213u32, 214u32, 215u32, 216u32, 217u32, 218u32, 219u32, 220u32, 241u32, 242u32, 243u32, 249u32, 303u32, 314u32, 324u32, 466u32];

pub fn is_typed_exact_decl_column(col: u32) -> bool {
    TYPED_EXACT_DECL_COLUMNS.contains(&col)
}

pub fn typed_exact_decl_for_column(col: u32) -> Option<HtmlDeclMeta> {
    Some(match col {
        0 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Religionen".to_string(), "Religionen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Sternpolygon".to_string()), Some("der_Tierkreiszeichen".to_string()), Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        1 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("babylonische_Tierkreiszeichen".to_string()), None], p4_tags: vec![3, 0] },
        2 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("babylonische_Tierkreiszeichen".to_string()), None], p4_tags: vec![3, 0] },
        3 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        4 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Grundstrukturen".to_string(), "Größenordnung".to_string(), "Universum".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Strukturgrösse".to_string()), Some("Strukturgrösse".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        5 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Universum".to_string(), "Universum".to_string(), "Universum".to_string(), "Grundstrukturen".to_string(), "Multiversum".to_string(), "Inkrementieren".to_string(), "Inkrementieren".to_string(), "Kontinuum".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Transzendentalien".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("O".to_string()), None], p4_tags: vec![4, 0] },
        6 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Sternpolygon".to_string()), None], p4_tags: vec![3, 0] },
        7 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Messias".to_string()), None], p4_tags: vec![3, 0] },
        8 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        9 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        10 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Paradigmen_sind_Absichten_(13)".to_string()), Some("Motive".to_string()), None], p4_tags: vec![3, 0] },
        11 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Errungenschaften".to_string()), None], p4_tags: vec![3, 0] },
        12 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), None], p4_tags: vec![3, 0] },
        13 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), Some("brauchen".to_string()), None], p4_tags: vec![3, 0] },
        14 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("brauchen".to_string()), None], p4_tags: vec![3, 0] },
        15 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("contra".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        16 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("gleichförmiges_Polygon".to_string()), None], p4_tags: vec![3, 1] },
        17 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Pro".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        18 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Motive".to_string()), None], p4_tags: vec![3, 0] },
        19 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("Zweitwichtigste".to_string()), Some("Primzahlen".to_string()), None], p4_tags: vec![3, 0] },
        20 => HtmlDeclMeta { p1_groups: vec!["Größenordnung".to_string(), "Licht".to_string()], p2_slots: vec![Some("Licht".to_string()), None, None], p4_tags: vec![3, 4, 0, 5] },
        21 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Größenordnung".to_string()], p2_slots: vec![Some("Strukturgrösse".to_string()), Some("Strukturgrösse".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        22 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Anwendung_der_Sonnen_und_Monde".to_string()), None], p4_tags: vec![3, 0] },
        23 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Vertreter_höherer_Konzepte".to_string()), None], p4_tags: vec![3, 0] },
        24 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("gegen_5".to_string()), Some("Krankheit".to_string()), None], p4_tags: vec![3, 0] },
        25 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Bedeutung".to_string(), "Kontinuum".to_string()], p2_slots: vec![Some("Netzwerk".to_string()), Some("Zählungen".to_string()), Some("X".to_string()), None], p4_tags: vec![4, 0] },
        26 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("contra".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        27 => HtmlDeclMeta { p1_groups: vec!["Größenordnung".to_string(), "Menschliches".to_string(), "Licht".to_string()], p2_slots: vec![Some("Licht".to_string()), Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), None, None], p4_tags: vec![4, 0] },
        28 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        29 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Gefühle_(7)".to_string()), Some("Anführer".to_string()), None], p4_tags: vec![3, 0] },
        30 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Größenordnung".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Zweitwichtigste".to_string()), Some("Organisationen".to_string()), Some("Berufe".to_string()), None], p4_tags: vec![3, 0] },
        31 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Lösungen".to_string()), None], p4_tags: vec![3, 0] },
        32 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), None], p4_tags: vec![3, 0] },
        33 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Stimmungen_Kombinationen_(14)".to_string()), Some("Musik".to_string()), None], p4_tags: vec![3, 0] },
        34 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("universelles_Recht".to_string()), Some("Jura".to_string()), None], p4_tags: vec![3, 0] },
        35 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Vollkommenheit_des_Geistes".to_string()), None], p4_tags: vec![3, 0] },
        36 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Religionen".to_string(), "Religionen".to_string(), "Symbole".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Sternpolygon".to_string()), Some("der_Tierkreiszeichen".to_string()), Some("Religionen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        37 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Religionen".to_string(), "Symbole".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("gleichförmiges_Polygon".to_string()), Some("Religionen".to_string()), None], p4_tags: vec![3, 5, 1, 4] },
        40 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Zahlenarten".to_string()), None], p4_tags: vec![0, 3] },
        41 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Bestrafung".to_string()), None], p4_tags: vec![0, 3] },
        44 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Erlösung".to_string()), None], p4_tags: vec![0, 3] },
        49 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("künstliches_Leben_(15)".to_string()), None], p4_tags: vec![0, 3] },
        50 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Software-Lizenzen_akademische_Grade".to_string()), None], p4_tags: vec![0, 3] },
        56 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Teilchen-Meta-Physik".to_string()), None], p4_tags: vec![0, 3] },
        60 => HtmlDeclMeta { p1_groups: vec!["Teilchen-Meta-Physik".to_string()], p2_slots: vec![Some("das_Multiverselle_(16)".to_string()), None], p4_tags: vec![0, 3] },
        61 => HtmlDeclMeta { p1_groups: vec!["Teilchen-Meta-Physik".to_string()], p2_slots: vec![Some("die_Tugendsortierung_(13_mit_14)".to_string()), None], p4_tags: vec![0, 3] },
        62 => HtmlDeclMeta { p1_groups: vec!["Teilchen-Meta-Physik".to_string()], p2_slots: vec![Some("die_Galaxie_Unterbereiche_(13)".to_string()), None], p4_tags: vec![0, 3] },
        63 => HtmlDeclMeta { p1_groups: vec!["Teilchen-Meta-Physik".to_string()], p2_slots: vec![Some("das_Gute_die_Richtung_(7)".to_string()), None], p4_tags: vec![0, 3] },
        42 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Reziprokes".to_string()), Some("Paradigmen_sind_Absichten_(13)".to_string()), Some("Motive".to_string()), None], p4_tags: vec![3, 1] },
        43 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![None, None], p4_tags: vec![3, 0] },
        45 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Zählungen".to_string()), None], p4_tags: vec![3, 0] },
        46 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("alpha_beta".to_string()), None], p4_tags: vec![3, 0] },
        47 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), None], p4_tags: vec![3, 0] },
        48 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Pro".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        51 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("dominierendes_Geschlecht".to_string()), None], p4_tags: vec![3, 0] },
        52 => HtmlDeclMeta { p1_groups: vec!["Eigenschaften_n".to_string()], p2_slots: vec![Some("gut_böse_lieb_schlecht".to_string()), None], p4_tags: vec![3, 1, 0] },
        53 => HtmlDeclMeta { p1_groups: vec!["Eigenschaften_n".to_string()], p2_slots: vec![Some("gut_böse_lieb_schlecht".to_string()), None], p4_tags: vec![3, 1, 0] },
        54 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Größenordnung".to_string(), "Universum".to_string(), "Universum".to_string(), "Inkrementieren".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("Strukturgrösse".to_string()), Some("Strukturgrösse".to_string()), Some("Transzendentalien".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), None, Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), None], p4_tags: vec![3, 4, 0] },
        55 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Universum".to_string(), "Kontinuum".to_string()], p2_slots: vec![Some("Transzendentalien".to_string()), Some("Netzwerk".to_string()), Some("X".to_string()), None], p4_tags: vec![4, 0] },
        57 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Angreifbarkeit".to_string()), None], p4_tags: vec![3, 0] },
        58 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Angreifbarkeit".to_string()), None], p4_tags: vec![3, 1] },
        59 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Glaube_Erkenntnis".to_string()), None], p4_tags: vec![3, 0] },
        64 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("Drittwichtigste".to_string()), Some("Gestirn".to_string()), None], p4_tags: vec![3, 0] },
        65 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Universum".to_string(), "Universum".to_string(), "Grundstrukturen".to_string(), "Universum".to_string(), "Multiversum".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("Zweitwichtigste".to_string()), Some("universelles_Recht".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), None], p4_tags: vec![4, 0] },
        68 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("INCELs".to_string()), None], p4_tags: vec![3, 0] },
        69 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Wirtschaft".to_string()], p2_slots: vec![Some("System".to_string()), Some("System".to_string()), None], p4_tags: vec![4, 0] },
        70 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Wirtschaft".to_string()], p2_slots: vec![Some("System".to_string()), Some("System".to_string()), None], p4_tags: vec![4, 0] },
        71 => HtmlDeclMeta { p1_groups: vec!["Wirtschaft".to_string()], p2_slots: vec![Some("Erklärung".to_string()), None], p4_tags: vec![3, 0] },
        72 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Religions-Gründer-Typ".to_string()), None], p4_tags: vec![3, 0] },
        73 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("irrationale_Zahlen_durch_Wurzelbildung".to_string()), None], p4_tags: vec![3, 0] },
        74 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![None, None], p4_tags: vec![3, 0] },
        75 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Universum".to_string(), "Multiversum".to_string()], p2_slots: vec![Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), None], p4_tags: vec![3, 4, 0] },
        76 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("4".to_string()), None], p4_tags: vec![3, 4, 0] },
        77 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Galaxie".to_string(), "Operationen".to_string()], p2_slots: vec![Some("Kugeln_Kreise".to_string()), Some("Kugeln_Kreise".to_string()), Some("4".to_string()), None], p4_tags: vec![4, 0] },
        78 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("2".to_string()), None], p4_tags: vec![3, 0] },
        79 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string(), "Planet_(10_und_oder_12)".to_string(), "Operationen".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Meta-Systeme_(12)".to_string()), Some("Gleichheit_Freiheit_Ordnung".to_string()), Some("2".to_string()), Some("Meta-Systeme_(12)".to_string()), None], p4_tags: vec![3, 0] },
        80 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string(), "Planet_(10_und_oder_12)".to_string(), "Operationen".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Meta-Systeme_(12)".to_string()), Some("Gleichheit_Freiheit_Ordnung".to_string()), Some("2".to_string()), Some("Meta-Systeme_(12)".to_string()), None], p4_tags: vec![4, 0] },
        81 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("4".to_string()), None], p4_tags: vec![4, 0] },
        82 => HtmlDeclMeta { p1_groups: vec!["Größenordnung".to_string()], p2_slots: vec![Some("Organisationen".to_string()), None], p4_tags: vec![3, 0] },
        83 => HtmlDeclMeta { p1_groups: vec!["Größenordnung".to_string()], p2_slots: vec![Some("politische_Systeme".to_string()), None], p4_tags: vec![3, 0] },
        84 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Galaxie".to_string(), "Universum".to_string()], p2_slots: vec![Some("analytische_Ontologie".to_string()), Some("analytische_Ontologie".to_string()), Some("analytische_Ontologie".to_string()), None], p4_tags: vec![4, 0] },
        86 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("Halbierung".to_string()), None], p4_tags: vec![3, 0] },
        87 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Sternpolygon_vs_gleichförmiges".to_string()), None], p4_tags: vec![3, 1, 0] },
        88 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Eigenschaften_n".to_string()], p2_slots: vec![Some("Sinn_des_Lebens".to_string()), Some("Sinn_und_Zweck_des_Lebens".to_string()), None], p4_tags: vec![3, 0] },
        89 => HtmlDeclMeta { p1_groups: vec!["Wirtschaft".to_string()], p2_slots: vec![Some("Maschinen".to_string()), None], p4_tags: vec![3, 0] },
        90 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Offenbarung_des_Johannes".to_string()), None], p4_tags: vec![3, 0] },
        91 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("chinesisches_Horoskop".to_string()), None], p4_tags: vec![3, 0] },
        92 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("3".to_string()), None], p4_tags: vec![3, 0] },
        93 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("3".to_string()), None], p4_tags: vec![4, 0] },
        94 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("9".to_string()), None], p4_tags: vec![4, 0] },
        95 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![None, None], p4_tags: vec![3, 0] },
        96 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("5".to_string()), None], p4_tags: vec![3, 0] },
        99 => HtmlDeclMeta { p1_groups: vec!["Wirtschaft".to_string()], p2_slots: vec![Some("Organisationsform".to_string()), None], p4_tags: vec![3, 0] },
        100 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Gegenteil".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        101 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Gegenteil".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        102 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Harmonie".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        103 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Harmonie".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        104 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("4".to_string()), None], p4_tags: vec![4, 0] },
        105 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Gefühle".to_string()), None], p4_tags: vec![3, 0] },
        106 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Konjunktiv_Wurzelbildung".to_string()), None], p4_tags: vec![3, 0] },
        107 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("Mechanismen".to_string()), Some("Mechanismen_der_Züchtung".to_string()), None], p4_tags: vec![4, 0, 5] },
        108 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Mechanismen_der_Züchtung".to_string()), None], p4_tags: vec![3, 0] },
        109 => HtmlDeclMeta { p1_groups: vec!["Wirtschaft".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("BWL".to_string()), Some("Mechanismen_der_Züchtung".to_string()), None], p4_tags: vec![3, 0] },
        112 => HtmlDeclMeta { p1_groups: vec!["Eigenschaften_n".to_string()], p2_slots: vec![Some("Weisheit_etc".to_string()), None], p4_tags: vec![3, 0] },
        113 => HtmlDeclMeta { p1_groups: vec!["Wirtschaft".to_string()], p2_slots: vec![Some("Pflanzen".to_string()), None], p4_tags: vec![3, 0] },
        114 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Hilfe_erhalten".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        115 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Helfen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        116 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Gegenposition".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        117 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("pro_nutzen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        118 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Vorzeichen".to_string()), None], p4_tags: vec![3, 0] },
        119 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Vorzeichen".to_string()), None], p4_tags: vec![3, 0] },
        120 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nervig".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        123 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nicht_miteinander_auskommen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        124 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nicht_dagegen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        125 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("kein_Gegenteil".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        126 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nicht_dafür".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        127 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Hilfe_nicht_gebrauchen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        128 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nicht_helfen_können".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        129 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("nicht_abgeneigt".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        130 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("unmotivierbar".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        131 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Grundstrukturen".to_string(), "Multiversum".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Reziproke_von_Transzendentalien".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("Reziprokes".to_string()), None], p4_tags: vec![4, 1] },
        132 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string(), "Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gleichheit_Freiheit_Ordnung".to_string()), Some("Gleichheit_Freiheit".to_string()), Some("Ordnung_und_Filterung_12_und_1pro12".to_string()), None], p4_tags: vec![4, 0, 5] },
        135 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Wirkung".to_string()), None], p4_tags: vec![3, 4, 0] },
        136 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Eigenschaften_n".to_string()], p2_slots: vec![Some("Egoismus".to_string()), Some("Egoismus_vs_Altruismus".to_string()), None], p4_tags: vec![3, 0] },
        137 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Gegenspieler".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        138 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Gegentranszendentalien".to_string()), Some("Gegentranszendentalien".to_string()), None], p4_tags: vec![4, 0] },
        139 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Gegentranszendentalien".to_string()), None], p4_tags: vec![3, 0] },
        140 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("ergibt_Sinn".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        141 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Vorteile".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        142 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Veränderung".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        143 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("bändigen_kontrollieren".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        144 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("vereinen".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        145 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Galaxie".to_string(), "Operationen".to_string()], p2_slots: vec![Some("Kugeln_Kreise".to_string()), Some("Kugeln_Kreise".to_string()), Some("4".to_string()), None], p4_tags: vec![3, 4, 0] },
        146 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Denkweise_von_Lebewesen".to_string()), None], p4_tags: vec![3, 0] },
        147 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Intelligenzprobleme".to_string()), None], p4_tags: vec![3, 0] },
        148 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Modallogik".to_string()), None], p4_tags: vec![3, 1] },
        149 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Transzendentalien_innen_außen".to_string()), Some("Motive".to_string()), None], p4_tags: vec![3, 4, 0] },
        150 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Systemsachen".to_string()), None], p4_tags: vec![3, 4, 0] },
        153 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Manipulation".to_string()), None], p4_tags: vec![3, 0] },
        154 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Gestirn".to_string()), None], p4_tags: vec![3, 1, 0] },
        155 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![Some("um1".to_string()), None], p4_tags: vec![3, 4, 0] },
        156 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![Some("um2".to_string()), None], p4_tags: vec![3, 4, 0] },
        157 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string()], p2_slots: vec![Some("um3".to_string()), None], p4_tags: vec![3, 4, 0] },
        158 => HtmlDeclMeta { p1_groups: vec!["Operationen".to_string()], p2_slots: vec![Some("Multiplikation".to_string()), None], p4_tags: vec![4, 0] },
        165 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), None], p4_tags: vec![3, 4, 0] },
        166 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), None], p4_tags: vec![3, 4, 0] },
        167 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Motive".to_string()), None], p4_tags: vec![3, 1, 0] },
        168 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Motive".to_string()), None], p4_tags: vec![3, 1, 0] },
        169 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Zählungen".to_string()), None], p4_tags: vec![4, 0] },
        170 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Anführer".to_string()), None], p4_tags: vec![3, 0] },
        183 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Menschliches".to_string(), "Wirtschaft".to_string()], p2_slots: vec![Some("Zweitwichtigste".to_string()), Some("Fachgebiete".to_string()), Some("Fachgebiete".to_string()), None], p4_tags: vec![3, 0] },
        188 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("Zählungen".to_string()), None], p4_tags: vec![3, 4, 0] },
        189 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Eigenschaften_n".to_string()], p2_slots: vec![Some("Sinn_des_Lebens".to_string()), Some("Sinn_und_Zweck_des_Lebens".to_string()), None], p4_tags: vec![3, 0] },
        190 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("keine_Nur-Paradigma-Religionen".to_string()), None], p4_tags: vec![4, 0] },
        191 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("keine_Nur-Paradigma-Religionen".to_string()), None], p4_tags: vec![4, 0] },
        196 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("keine_Nur-Paradigma-Religionen".to_string()), None], p4_tags: vec![4, 0] },
        197 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Größenordnung".to_string()], p2_slots: vec![Some("Strukturgrösse".to_string()), Some("Strukturgrösse".to_string()), None], p4_tags: vec![3, 5, 1, 4] },
        198 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Transzendentalien".to_string()), None], p4_tags: vec![4, 0] },
        201 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string()], p2_slots: vec![Some("Reziproke_von_Transzendentalien".to_string()), None], p4_tags: vec![4, 1] },
        202 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Gegentranszendentalien".to_string()), Some("Gegentranszendentalien".to_string()), None], p4_tags: vec![4, 0] },
        203 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Universum".to_string(), "Multiversum".to_string()], p2_slots: vec![Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), Some("Model_of_Hierarchical_Complexity".to_string()), None], p4_tags: vec![4, 1] },
        204 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Grundstrukturen".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Kategorie".to_string()), Some("Reziprokes".to_string()), Some("Reflektion_und_Kategorien_(1/15)".to_string()), None], p4_tags: vec![4, 0, 5] },
        205 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Grundstrukturen".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Kategorie".to_string()), Some("Reziprokes".to_string()), Some("Reflektion_und_Kategorien_(1/15)".to_string()), None], p4_tags: vec![1, 4, 5] },
        207 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Religionen".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("der_Tierkreiszeichen".to_string()), None], p4_tags: vec![3, 0] },
        208 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        209 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("in_ReTa".to_string()), None], p4_tags: vec![4, 0] },
        210 => HtmlDeclMeta { p1_groups: vec!["Bedeutung".to_string()], p2_slots: vec![Some("in_ReTa".to_string()), None], p4_tags: vec![4, 0] },
        213 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string()], p2_slots: vec![Some("Komplexität".to_string()), None], p4_tags: vec![4, 0, 5] },
        214 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string()], p2_slots: vec![Some("Intelligenz".to_string()), None], p4_tags: vec![4, 0, 5] },
        215 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Moral".to_string()), None], p4_tags: vec![3, 0] },
        216 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Moral".to_string()), None], p4_tags: vec![3, 4, 1, 0] },
        217 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Hinduismus".to_string()), None], p4_tags: vec![3, 0] },
        218 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Raum-Missionen".to_string()), Some("Raum-Missionen".to_string()), None], p4_tags: vec![3, 4, 0] },
        219 => HtmlDeclMeta { p1_groups: vec!["Inkrementieren".to_string(), "Universum".to_string(), "Teilchen-Meta-Physik".to_string()], p2_slots: vec![Some("Teilchen-Meta-Physik".to_string()), Some("Teilchen-Meta-Physik".to_string()), Some("das_Universelle_(15)".to_string()), None], p4_tags: vec![4, 0] },
        220 => HtmlDeclMeta { p1_groups: vec!["Eigenschaften_n".to_string()], p2_slots: vec![Some("ähnlich".to_string()), None], p4_tags: vec![3, 4, 0] },
        241 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gesellschaftsschicht".to_string()), Some("Klassen_(20)".to_string()), None], p4_tags: vec![3, 0, 5] },
        242 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Grundstrukturen".to_string(), "Grundstrukturen".to_string(), "Multiversum".to_string()], p2_slots: vec![Some("Geist__(15)".to_string()), Some("nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)".to_string()), Some("Geist_(15)".to_string()), Some("Geist_(15)".to_string()), None], p4_tags: vec![4, 0] },
        243 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gefühle".to_string()), Some("Gefühle_(7)".to_string()), None], p4_tags: vec![0, 5] },
        249 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Gedanken_sind_Positionen_(17)".to_string()), Some("Gedanken_sind_Positionen_(17)".to_string()), None], p4_tags: vec![0, 5] },
        303 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        314 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Mensch-zu-Tier".to_string()), None], p4_tags: vec![4, 0, 5] },
        324 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string()], p2_slots: vec![Some("Gleichheit_Freiheit_Ordnung".to_string()), None], p4_tags: vec![0, 5] },
        466 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gewalt".to_string()), Some("Gewalt".to_string()), None], p4_tags: vec![3, 4, 0] },
        _ => return None,
    })
}

pub fn all_typed_exact_decls() -> Vec<(u32, HtmlDeclMeta)> {
    TYPED_EXACT_DECL_COLUMNS
        .iter()
        .filter_map(|&col| typed_exact_decl_for_column(col).map(|meta| (col, meta)))
        .collect()
}
