use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

const CORE_SPLIT_LIBS: &[&str] = &[
    "reta_data",
    "reta_parse",
    "reta_semantics",
    "reta_table",
    "reta_render",
    "reta_arch",
    "reta_runtime",
];

fn target_profile_dir() -> PathBuf {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    for ancestor in out_dir.ancestors() {
        if ancestor.file_name() == Some(OsStr::new("build")) {
            if let Some(parent) = ancestor.parent() {
                return parent.to_path_buf();
            }
        }
    }

    let profile = env::var("PROFILE").unwrap_or_else(|_| "release".to_string());
    if let Ok(target_dir) = env::var("CARGO_TARGET_DIR") {
        return PathBuf::from(target_dir).join(profile);
    }
    PathBuf::from("target").join(profile)
}

fn main() {
    let repo_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo"));
    generate_embedded_csv_assets(&repo_root);

    println!("cargo:rerun-if-env-changed=RETA_LINK_CORE_SPLIT_LIBS");
    println!("cargo:rustc-check-cfg=cfg(reta_link_core_split_libs)");
    println!("cargo:rustc-check-cfg=cfg(reta_runtime_core_carrier)");

    if env::var("RETA_LINK_CORE_SPLIT_LIBS").ok().as_deref() != Some("1") {
        return;
    }

    let target_dir = target_profile_dir();
    println!("cargo:rustc-cfg=reta_link_core_split_libs");
    println!("cargo:rustc-link-search=native={}", target_dir.display());
    println!("cargo:rustc-cdylib-link-arg=-Wl,-rpath,$ORIGIN");
    println!("cargo:rustc-cdylib-link-arg=-Wl,-rpath,$ORIGIN/lib");
    println!("cargo:rustc-cdylib-link-arg=-Wl,-rpath,$ORIGIN/../lib");

    for lib in CORE_SPLIT_LIBS {
        println!("cargo:rustc-link-lib=dylib={lib}");
    }
}

#[derive(Debug)]
struct EmbeddedCsvBuildAsset {
    name: String,
    path: PathBuf,
    len: usize,
    fnv1a64: u64,
}

#[derive(Debug)]
struct EmbeddedCsvBuildAlias {
    name: String,
    target: String,
}

fn generate_embedded_csv_assets(repo_root: &Path) {
    let csv_dir = repo_root.join("csv");
    println!("cargo:rerun-if-changed={}", csv_dir.display());

    let (mut assets, mut aliases) = collect_embedded_csv_entries(&csv_dir);
    assets.sort_by(|left, right| left.name.cmp(&right.name));
    aliases.sort_by(|left, right| left.name.cmp(&right.name));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let generated_path = out_dir.join("reta_embedded_csv_assets.rs");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit.\n");
    generated.push_str("#[derive(Clone, Copy, Debug)]\n");
    generated.push_str("pub struct EmbeddedCsvAsset {\n");
    generated.push_str("    pub name: &'static str,\n");
    generated.push_str("    pub bytes: &'static [u8],\n");
    generated.push_str("    pub len: usize,\n");
    generated.push_str("    pub fnv1a64: u64,\n");
    generated.push_str("}\n\n");
    generated.push_str("#[derive(Clone, Copy, Debug)]\n");
    generated.push_str("pub struct EmbeddedCsvAlias {\n");
    generated.push_str("    pub name: &'static str,\n");
    generated.push_str("    pub target: &'static str,\n");
    generated.push_str("}\n\n");
    generated.push_str("pub static EMBEDDED_CSV_ASSETS: &[EmbeddedCsvAsset] = &[\n");

    for asset in assets {
        let include_path = asset.path.to_string_lossy();
        generated.push_str("    EmbeddedCsvAsset {\n");
        generated.push_str(&format!("        name: {:?},\n", asset.name));
        generated.push_str(&format!("        bytes: include_bytes!({include_path:?}),\n"));
        generated.push_str(&format!("        len: {},\n", asset.len));
        generated.push_str(&format!("        fnv1a64: 0x{:016x},\n", asset.fnv1a64));
        generated.push_str("    },\n");
    }

    generated.push_str("];\n\n");
    generated.push_str("pub static EMBEDDED_CSV_ALIASES: &[EmbeddedCsvAlias] = &[\n");
    for alias in aliases {
        generated.push_str("    EmbeddedCsvAlias {\n");
        generated.push_str(&format!("        name: {:?},\n", alias.name));
        generated.push_str(&format!("        target: {:?},\n", alias.target));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    fs::write(&generated_path, generated)
        .unwrap_or_else(|err| panic!("cannot write {}: {err}", generated_path.display()));
}

fn collect_embedded_csv_entries(csv_dir: &Path) -> (Vec<EmbeddedCsvBuildAsset>, Vec<EmbeddedCsvBuildAlias>) {
    let read_dir = fs::read_dir(csv_dir)
        .unwrap_or_else(|err| panic!("cannot read compile-time CSV directory {}: {err}", csv_dir.display()));
    let mut candidates = read_dir
        .map(|entry| entry.unwrap_or_else(|err| panic!("cannot read CSV directory entry: {err}")))
        .filter(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("csv"))
        .collect::<Vec<_>>();
    candidates.sort_by_key(|entry| entry.file_name());

    let mut assets = Vec::new();
    let mut aliases = Vec::new();
    let mut seen_content: Vec<((usize, u64), String)> = Vec::new();

    for entry in candidates {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();

        if let Ok(metadata) = fs::symlink_metadata(&path) {
            if metadata.file_type().is_symlink() {
                let target = fs::read_link(&path)
                    .unwrap_or_else(|err| panic!("cannot read CSV symlink {}: {err}", path.display()));
                let target_name = target
                    .file_name()
                    .and_then(|value| value.to_str())
                    .unwrap_or_else(|| panic!("CSV symlink {} has no UTF-8 file target", path.display()))
                    .to_string();
                if name != target_name {
                    println!("cargo:rerun-if-changed={}", path.display());
                    aliases.push(EmbeddedCsvBuildAlias { name, target: target_name });
                    continue;
                }
            }
        }

        let bytes = fs::read(&path)
            .unwrap_or_else(|err| panic!("cannot read compile-time CSV file {}: {err}", path.display()));
        let len = bytes.len();
        let fnv1a64 = fnv1a64(&bytes);
        if let Some((_, existing_name)) = seen_content
            .iter()
            .find(|((seen_len, seen_hash), _)| *seen_len == len && *seen_hash == fnv1a64)
        {
            println!("cargo:rerun-if-changed={}", path.display());
            aliases.push(EmbeddedCsvBuildAlias {
                name,
                target: existing_name.clone(),
            });
            continue;
        }

        let include_path = fs::canonicalize(&path).unwrap_or(path);
        println!("cargo:rerun-if-changed={}", include_path.display());
        seen_content.push(((len, fnv1a64), name.clone()));
        assets.push(EmbeddedCsvBuildAsset {
            name,
            path: include_path,
            len,
            fnv1a64,
        });
    }

    if assets.is_empty() {
        panic!("compile-time CSV directory {} does not contain any real *.csv files", csv_dir.display());
    }

    (assets, aliases)
}

fn fnv1a64(data: &[u8]) -> u64 {
    let mut value = 0xcbf29ce484222325u64;
    for byte in data {
        value ^= u64::from(*byte);
        value = value.wrapping_mul(0x100000001b3);
    }
    value
}
