[package]
name = "reta"
version = "0.1.0"
edition = "2024"
autobins = false
default-run = "reta"

[dependencies]
indexmap = "2"
hypher = { version = "0.1.7", default-features = false, features = ["german"] }
termimad = "0.34.1"
reedline = "0.47.0"
ratatui = { version = "0.30.0", features = ["crossterm"] }
crossterm = "0.29.0"
nu-ansi-term = "0.50.3"

[lib]
name = "reta"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "reta"
path = "src/bin/reta.rs"

[[bin]]
name = "grundStrukHtml"
path = "src/bin/grundStrukHtml.rs"

[[bin]]
name = "generate4readme"
path = "src/bin/generate4readme.rs"

[[bin]]
name = "rp"
path = "src/bin/rp.rs"

[[bin]]
name = "rpl"
path = "src/bin/rpl.rs"

[[bin]]
name = "rpb"
path = "src/bin/rpb.rs"

[[bin]]
name = "rpe"
path = "src/bin/rpe.rs"

[[bin]]
name = "reta_domain_probe"
path = "src/bin/reta_domain_probe.rs"



[workspace]
members = ["crates/retaprompt", "crates/retaprompt_frontends", "crates/retaprompt_input", "crates/retaprompt_commands"]
resolver = "2"
