[package]
name = "reta"
version = "0.5.0"
edition = "2024"
autobins = false
default-run = "reta"

[dependencies]
indexmap = { version = "2", features = ["serde"] }
hypher = { version = "0.1.7", default-features = false, features = ["german"] }
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "reta"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "reta"
path = "src/bin/reta.rs"

[[bin]]
name = "grundStrukHtml"
path = "src/bin/grundStrukHtml.rs"

[[bin]]
name = "generate4readme"
path = "src/bin/generate4readme.rs"

[[bin]]
name = "reta_domain_probe"
path = "src/bin/reta_domain_probe.rs"


[workspace]
members = [
  ".",
  "crates/retaprompt_input",
  "crates/retaprompt_commands",
  "crates/retaprompt_frontends"
]
default-members = [
  ".",
  "crates/retaprompt_input",
  "crates/retaprompt_commands",
  "crates/retaprompt_frontends"
]
resolver = "2"
