[package]
name = "mein-rpnn"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
fluent-templates = "0.9"
# Notwendig für die Sprach-Identifikation (z.B. langid!("de"))
unic-langid = "0.9"
terminal_size = "0.4"
comfy-table = "7.2.2"
#prettytable = "0.10.0"
unicode-width = "0.1"

[[bin]]
name = "mein-rpnn"
path = "src/main.rs"

