#!/bin/zsh
if [[ "${1}" == "t" ]]
then
  rpnn --vorhervonausschnitt ${2} --spaltenname Galaxie thomas --spaltenreihenfolgeundnurdiese 2
  primfaktors ${2}
fi
if [[ "${1}" == "a" ]]
then
  rpnn --vorhervonausschnitt ${2} --spaltenname Menschliches motive --spaltenreihenfolgeundnurdiese 1
  primfaktors ${2}
fi
if [[ "${1}" == "at" || "${1}" == "ta" ]]
then
  rpnn --vorhervonausschnitt ${2} --spaltenname Menschliches motive  --spaltenname Galaxie thomas --spaltenreihenfolgeundnurdiese 2,3 --breite 30
  primfaktors ${2}
fi
if [[ "${1}" == "Kontinuum" || "${1}" == "kontinuum" ]]
then
  rpnn --vorhervonausschnitt ${3} --spaltenname Kontinuum ${2}
  primfaktors ${2}
fi

