use crate::domain::decl_model::HtmlDeclMeta;

fn decl(p1: &[&str], p2: &[Option<&str>], p4: &[u8]) -> HtmlDeclMeta {
    HtmlDeclMeta {
        p1_groups: p1.iter().map(|s| (*s).to_string()).collect(),
        p2_slots: p2.iter().map(|opt| opt.map(|s| s.to_string())).collect(),
        p4_tags: p4.to_vec(),
    }
}

pub const TYPED_EXACT_DECL_COLUMNS: &[u32] = &[
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    28,
    42, 43, 45, 46, 47, 48, 51, 52, 53, 54, 55, 57, 58, 59,
    64, 65, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
    86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 99, 100,
    101, 102, 103, 104, 105, 106, 107, 108, 109,
    112, 113, 114, 115, 116, 117, 118, 119, 120,
    123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
    135, 136, 137, 138, 139, 140,
    241, 242, 243, 249, 303, 314, 324, 466,
];

pub fn is_typed_exact_decl_column(col: u32) -> bool {
    TYPED_EXACT_DECL_COLUMNS.contains(&col)
}

pub fn typed_exact_decl_for_column(col: u32) -> Option<HtmlDeclMeta> {
    Some(match col {
        0 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Religionen".to_string(), "Religionen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Sternpolygon".to_string()), Some("der_Tierkreiszeichen".to_string()), Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        1 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("babylonische_Tierkreiszeichen".to_string()), None], p4_tags: vec![3, 0] },
        2 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_gedanklich_einordnen".to_string(), "Galaxie".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("babylonische_Tierkreiszeichen".to_string()), None], p4_tags: vec![3, 0] },
        3 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        4 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Grundstrukturen".to_string(), "Größenordnung".to_string(), "Universum".to_string(), "Inkrementieren".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Strukturgrösse".to_string()), Some("Strukturgrösse".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        5 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Universum".to_string(), "Universum".to_string(), "Universum".to_string(), "Grundstrukturen".to_string(), "Multiversum".to_string(), "Inkrementieren".to_string(), "Inkrementieren".to_string(), "Kontinuum".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Transzendentalien".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)".to_string()), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter".to_string()), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons".to_string()), Some("O".to_string()), None], p4_tags: vec![4, 0] },
        6 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Sternpolygon".to_string()), None], p4_tags: vec![3, 0] },
        7 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("Messias".to_string()), None], p4_tags: vec![3, 0] },
        8 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        9 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        10 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Wichtigste".to_string()), Some("Paradigmen_sind_Absichten_(13)".to_string()), Some("Motive".to_string()), None], p4_tags: vec![3, 0] },
        11 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Errungenschaften".to_string()), None], p4_tags: vec![3, 0] },
        12 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), None], p4_tags: vec![3, 0] },
        13 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("evolutionär_erwerben_und_Intelligenz_Kreativität".to_string()), Some("brauchen".to_string()), None], p4_tags: vec![3, 0] },
        14 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("brauchen".to_string()), None], p4_tags: vec![3, 0] },
        15 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("contra".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        16 => HtmlDeclMeta { p1_groups: vec!["Religionen".to_string()], p2_slots: vec![Some("gleichförmiges_Polygon".to_string()), None], p4_tags: vec![3, 1] },
        17 => HtmlDeclMeta { p1_groups: vec!["Pro_Contra".to_string()], p2_slots: vec![Some("Pro".to_string()), None], p4_tags: vec![3, 4, 0, 5] },
        18 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Motive".to_string()), None], p4_tags: vec![3, 0] },
        19 => HtmlDeclMeta { p1_groups: vec!["Wichtigstes_zum_verstehen".to_string(), "Bedeutung".to_string()], p2_slots: vec![Some("Zweitwichtigste".to_string()), Some("Primzahlen".to_string()), None], p4_tags: vec![3, 0] },
        20 => HtmlDeclMeta { p1_groups: vec!["Größenordnung".to_string(), "Licht".to_string()], p2_slots: vec![Some("Licht".to_string()), None, None], p4_tags: vec![3, 4, 0, 5] },
        28 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Liebe".to_string()), Some("Liebe_(7)".to_string()), None], p4_tags: vec![0, 5] },
        42 => decl(&["Grundstrukturen", "Grundstrukturen", "Menschliches"], &[Some("Reziprokes"), Some("Paradigmen_sind_Absichten_(13)"), Some("Motive"), None], &[3, 1]),
        43 => decl(&["Inkrementieren"], &[None, None], &[3, 0]),
        45 => decl(&["Bedeutung"], &[Some("Zählungen"), None], &[3, 0]),
        46 => decl(&["Menschliches"], &[Some("alpha_beta"), None], &[3, 0]),
        47 => decl(&["Menschliches"], &[Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), None], &[3, 0]),
        48 => decl(&["Pro_Contra"], &[Some("Pro"), None], &[3, 4, 0, 5]),
        51 => decl(&["Menschliches"], &[Some("dominierendes_Geschlecht"), None], &[3, 0]),
        52 => decl(&["Eigenschaften_n"], &[Some("gut_böse_lieb_schlecht"), None], &[3, 1, 0]),
        53 => decl(&["Eigenschaften_n"], &[Some("gut_böse_lieb_schlecht"), None], &[3, 1, 0]),
        54 => decl(&["Grundstrukturen", "Größenordnung", "Universum", "Universum", "Inkrementieren", "Inkrementieren"], &[Some("Strukturgrösse"), Some("Strukturgrösse"), Some("Transzendentalien"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), None, Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), None], &[3, 4, 0]),
        55 => decl(&["Universum", "Universum", "Kontinuum"], &[Some("Transzendentalien"), Some("Netzwerk"), Some("X"), None], &[4, 0]),
        57 => decl(&["Menschliches"], &[Some("Angreifbarkeit"), None], &[3, 0]),
        58 => decl(&["Menschliches"], &[Some("Angreifbarkeit"), None], &[3, 1]),
        59 => decl(&["Menschliches"], &[Some("Glaube_Erkenntnis"), None], &[3, 0]),
        64 => decl(&["Wichtigstes_zum_verstehen", "Bedeutung"], &[Some("Drittwichtigste"), Some("Gestirn"), None], &[3, 0]),
        65 => decl(&["Wichtigstes_zum_verstehen", "Universum", "Universum", "Grundstrukturen", "Universum", "Multiversum", "Inkrementieren"], &[Some("Zweitwichtigste"), Some("universelles_Recht"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), None], &[4, 0]),
        68 => decl(&["Menschliches"], &[Some("INCELs"), None], &[3, 0]),
        69 => decl(&["Grundstrukturen", "Wirtschaft"], &[Some("System"), Some("System"), None], &[4, 0]),
        70 => decl(&["Grundstrukturen", "Wirtschaft"], &[Some("System"), Some("System"), None], &[4, 0]),
        71 => decl(&["Wirtschaft"], &[Some("Erklärung"), None], &[3, 0]),
        72 => decl(&["Religionen"], &[Some("Religions-Gründer-Typ"), None], &[3, 0]),
        73 => decl(&["Menschliches"], &[Some("irrationale_Zahlen_durch_Wurzelbildung"), None], &[3, 0]),
        74 => decl(&["Inkrementieren"], &[None, None], &[3, 0]),
        75 => decl(&["Grundstrukturen", "Universum", "Multiversum"], &[Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), None], &[3, 4, 0]),
        76 => decl(&["Operationen"], &[Some("4"), None], &[3, 4, 0]),
        77 => decl(&["Universum", "Galaxie", "Operationen"], &[Some("Kugeln_Kreise"), Some("Kugeln_Kreise"), Some("4"), None], &[4, 0]),
        78 => decl(&["Operationen"], &[Some("2"), None], &[3, 0]),
        79 => decl(&["Planet_(10_und_oder_12)", "Planet_(10_und_oder_12)", "Operationen", "Grundstrukturen"], &[Some("Meta-Systeme_(12)"), Some("Gleichheit_Freiheit_Ordnung"), Some("2"), Some("Meta-Systeme_(12)"), None], &[3, 0]),
        80 => decl(&["Planet_(10_und_oder_12)", "Planet_(10_und_oder_12)", "Operationen", "Grundstrukturen"], &[Some("Meta-Systeme_(12)"), Some("Gleichheit_Freiheit_Ordnung"), Some("2"), Some("Meta-Systeme_(12)"), None], &[4, 0]),
        81 => decl(&["Operationen"], &[Some("4"), None], &[4, 0]),
        82 => decl(&["Größenordnung"], &[Some("Organisationen"), None], &[3, 0]),
        83 => decl(&["Größenordnung"], &[Some("politische_Systeme"), None], &[3, 0]),
        84 => decl(&["Grundstrukturen", "Galaxie", "Universum"], &[Some("analytische_Ontologie"), Some("analytische_Ontologie"), Some("analytische_Ontologie"), None], &[4, 0]),
        86 => decl(&["Operationen"], &[Some("Halbierung"), None], &[3, 0]),
        87 => decl(&["Religionen"], &[Some("Sternpolygon_vs_gleichförmiges"), None], &[3, 1, 0]),
        88 => decl(&["Menschliches", "Eigenschaften_n"], &[Some("Sinn_des_Lebens"), Some("Sinn_und_Zweck_des_Lebens"), None], &[3, 0]),
        89 => decl(&["Wirtschaft"], &[Some("Maschinen"), None], &[3, 0]),
        90 => decl(&["Galaxie"], &[Some("Offenbarung_des_Johannes"), None], &[3, 0]),
        91 => decl(&["Galaxie"], &[Some("chinesisches_Horoskop"), None], &[3, 0]),
        92 => decl(&["Operationen"], &[Some("3"), None], &[3, 0]),
        93 => decl(&["Operationen"], &[Some("3"), None], &[4, 0]),
        94 => decl(&["Operationen"], &[Some("9"), None], &[4, 0]),
        95 => decl(&["Inkrementieren"], &[None, None], &[3, 0]),
        96 => decl(&["Operationen"], &[Some("5"), None], &[3, 0]),
        99 => decl(&["Wirtschaft"], &[Some("Organisationsform"), None], &[3, 0]),
        100 => decl(&["Pro_Contra"], &[Some("Gegenteil"), None], &[3, 4, 0, 5]),
        101 => decl(&["Pro_Contra"], &[Some("Gegenteil"), None], &[3, 4, 0, 5]),
        102 => decl(&["Pro_Contra"], &[Some("Harmonie"), None], &[3, 4, 0, 5]),
        103 => decl(&["Pro_Contra"], &[Some("Harmonie"), None], &[3, 4, 0, 5]),
        104 => decl(&["Operationen"], &[Some("4"), None], &[4, 0]),
        105 => decl(&["Menschliches"], &[Some("Gefühle"), None], &[3, 0]),
        106 => decl(&["Bedeutung"], &[Some("Konjunktiv_Wurzelbildung"), None], &[3, 0]),
        107 => decl(&["Planet_(10_und_oder_12)", "Bedeutung"], &[Some("Mechanismen"), Some("Mechanismen_der_Züchtung"), None], &[4, 0, 5]),
        108 => decl(&["Bedeutung"], &[Some("Mechanismen_der_Züchtung"), None], &[3, 0]),
        109 => decl(&["Wirtschaft", "Bedeutung"], &[Some("BWL"), Some("Mechanismen_der_Züchtung"), None], &[3, 0]),
        112 => decl(&["Eigenschaften_n"], &[Some("Weisheit_etc"), None], &[3, 0]),
        113 => decl(&["Wirtschaft"], &[Some("Pflanzen"), None], &[3, 0]),
        114 => decl(&["Pro_Contra"], &[Some("Hilfe_erhalten"), None], &[3, 4, 0, 5]),
        115 => decl(&["Pro_Contra"], &[Some("Helfen"), None], &[3, 4, 0, 5]),
        116 => decl(&["Pro_Contra"], &[Some("Gegenposition"), None], &[3, 4, 0, 5]),
        117 => decl(&["Pro_Contra"], &[Some("pro_nutzen"), None], &[3, 4, 0, 5]),
        118 => decl(&["Bedeutung"], &[Some("Vorzeichen"), None], &[3, 0]),
        119 => decl(&["Bedeutung"], &[Some("Vorzeichen"), None], &[3, 0]),
        120 => decl(&["Pro_Contra"], &[Some("nervig"), None], &[3, 4, 0, 5]),
        123 => decl(&["Pro_Contra"], &[Some("nicht_miteinander_auskommen"), None], &[3, 4, 0, 5]),
        124 => decl(&["Pro_Contra"], &[Some("nicht_dagegen"), None], &[3, 4, 0, 5]),
        125 => decl(&["Pro_Contra"], &[Some("kein_Gegenteil"), None], &[3, 4, 0, 5]),
        126 => decl(&["Pro_Contra"], &[Some("nicht_dafür"), None], &[3, 4, 0, 5]),
        127 => decl(&["Pro_Contra"], &[Some("Hilfe_nicht_gebrauchen"), None], &[3, 4, 0, 5]),
        128 => decl(&["Pro_Contra"], &[Some("nicht_helfen_können"), None], &[3, 4, 0, 5]),
        129 => decl(&["Pro_Contra"], &[Some("nicht_abgeneigt"), None], &[3, 4, 0, 5]),
        130 => decl(&["Pro_Contra"], &[Some("unmotivierbar"), None], &[3, 4, 0, 5]),
        131 => decl(&["Universum", "Grundstrukturen", "Multiversum", "Grundstrukturen"], &[Some("Reziproke_von_Transzendentalien"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("Reziprokes"), None], &[4, 1]),
        132 => decl(&["Planet_(10_und_oder_12)", "Menschliches", "Grundstrukturen"], &[Some("Gleichheit_Freiheit_Ordnung"), Some("Gleichheit_Freiheit"), Some("Ordnung_und_Filterung_12_und_1pro12"), None], &[4, 0, 5]),
        135 => decl(&["Menschliches"], &[Some("Wirkung"), None], &[3, 4, 0]),
        136 => decl(&["Menschliches", "Eigenschaften_n"], &[Some("Egoismus"), Some("Egoismus_vs_Altruismus"), None], &[3, 0]),
        137 => decl(&["Pro_Contra"], &[Some("Gegenspieler"), None], &[3, 4, 0, 5]),
        138 => decl(&["Universum", "Menschliches"], &[Some("Gegentranszendentalien"), Some("Gegentranszendentalien"), None], &[4, 0]),
        139 => decl(&["Menschliches"], &[Some("Gegentranszendentalien"), None], &[3, 0]),
        140 => decl(&["Pro_Contra"], &[Some("ergibt_Sinn"), None], &[3, 4, 0, 5]),
        241 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gesellschaftsschicht".to_string()), Some("Klassen_(20)".to_string()), None], p4_tags: vec![3, 0, 5] },
        242 => HtmlDeclMeta { p1_groups: vec!["Universum".to_string(), "Grundstrukturen".to_string(), "Grundstrukturen".to_string(), "Multiversum".to_string()], p2_slots: vec![Some("Geist__(15)".to_string()), Some("nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)".to_string()), Some("Geist_(15)".to_string()), Some("Geist_(15)".to_string()), None], p4_tags: vec![4, 0] },
        243 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gefühle".to_string()), Some("Gefühle_(7)".to_string()), None], p4_tags: vec![0, 5] },
        249 => HtmlDeclMeta { p1_groups: vec!["Grundstrukturen".to_string(), "Menschliches".to_string()], p2_slots: vec![Some("Gedanken_sind_Positionen_(17)".to_string()), Some("Gedanken_sind_Positionen_(17)".to_string()), None], p4_tags: vec![0, 5] },
        303 => HtmlDeclMeta { p1_groups: vec!["Galaxie".to_string()], p2_slots: vec![Some("Thomasevangelium".to_string()), None], p4_tags: vec![3, 0] },
        314 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string()], p2_slots: vec![Some("Mensch-zu-Tier".to_string()), None], p4_tags: vec![4, 0, 5] },
        324 => HtmlDeclMeta { p1_groups: vec!["Planet_(10_und_oder_12)".to_string()], p2_slots: vec![Some("Gleichheit_Freiheit_Ordnung".to_string()), None], p4_tags: vec![0, 5] },
        466 => HtmlDeclMeta { p1_groups: vec!["Menschliches".to_string(), "Grundstrukturen".to_string()], p2_slots: vec![Some("Gewalt".to_string()), Some("Gewalt".to_string()), None], p4_tags: vec![3, 4, 0] },
        _ => return None,
    })
}

pub fn all_typed_exact_decls() -> Vec<(u32, HtmlDeclMeta)> {
    TYPED_EXACT_DECL_COLUMNS
        .iter()
        .filter_map(|&col| typed_exact_decl_for_column(col).map(|meta| (col, meta)))
        .collect()
}
