use crate::domain::decl_model::HtmlDeclMeta;

pub const TYPED_EXACT_DECL_COLUMNS: &[u32] = &[
    0u32, 1u32, 2u32, 3u32, 4u32, 5u32, 6u32, 7u32, 8u32, 9u32, 10u32, 11u32,
    12u32, 13u32, 14u32, 15u32, 16u32, 17u32, 18u32, 19u32, 20u32, 21u32, 22u32, 23u32,
    24u32, 25u32, 26u32, 27u32, 28u32, 29u32, 30u32, 31u32, 32u32, 33u32, 34u32, 35u32,
    36u32, 37u32, 42u32, 43u32, 45u32, 46u32, 47u32, 48u32, 51u32, 52u32, 53u32, 54u32,
    55u32, 57u32, 58u32, 59u32, 64u32, 65u32, 68u32, 69u32, 70u32, 71u32, 72u32, 73u32,
    74u32, 75u32, 76u32, 77u32, 78u32, 79u32, 80u32, 81u32, 82u32, 83u32, 84u32, 86u32,
    87u32, 88u32, 89u32, 90u32, 91u32, 92u32, 93u32, 94u32, 95u32, 96u32, 99u32, 100u32,
    101u32, 102u32, 103u32, 104u32, 105u32, 106u32, 107u32, 108u32, 109u32, 112u32, 113u32, 114u32,
    115u32, 116u32, 117u32, 118u32, 119u32, 120u32, 123u32, 124u32, 125u32, 126u32, 127u32, 128u32,
    129u32, 130u32, 131u32, 132u32, 135u32, 136u32, 137u32, 138u32, 139u32, 140u32, 241u32, 242u32,
    243u32, 249u32, 303u32, 314u32, 324u32, 466u32,
];

pub fn is_typed_exact_decl_column(col: u32) -> bool {
    TYPED_EXACT_DECL_COLUMNS.binary_search(&col).is_ok()
}

fn decl(p1: &[&str], p2: &[Option<&str>], p4: &[u8]) -> HtmlDeclMeta {
    HtmlDeclMeta {
        p1_groups: p1.iter().map(|s| (*s).to_string()).collect(),
        p2_slots: p2.iter().map(|s| s.map(|v| v.to_string())).collect(),
        p4_tags: p4.to_vec(),
    }
}

pub fn typed_exact_decl_for_column(col: u32) -> Option<HtmlDeclMeta> {
    match col {
        0u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Religionen", "Religionen", "Galaxie"], &[Some("Wichtigste"), Some("Sternpolygon"), Some("der_Tierkreiszeichen"), Some("Thomasevangelium"), None], &[3u8, 0u8])),
        1u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Galaxie"], &[Some("Wichtigste"), Some("babylonische_Tierkreiszeichen"), None], &[3u8, 0u8])),
        2u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Galaxie"], &[Some("Wichtigste"), Some("babylonische_Tierkreiszeichen"), None], &[3u8, 0u8])),
        3u32 => Some(decl(&["Galaxie"], &[Some("Thomasevangelium"), None], &[3u8, 0u8])),
        4u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Grundstrukturen", "Größenordnung", "Universum", "Inkrementieren"], &[Some("Wichtigste"), Some("Strukturgrösse"), Some("Strukturgrösse"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), None], &[3u8, 4u8, 0u8, 5u8])),
        5u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Universum", "Universum", "Universum", "Grundstrukturen", "Multiversum", "Inkrementieren", "Inkrementieren", "Kontinuum"], &[Some("Wichtigste"), Some("Transzendentalien"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), Some("O"), None], &[4u8, 0u8])),
        6u32 => Some(decl(&["Religionen"], &[Some("Sternpolygon"), None], &[3u8, 0u8])),
        7u32 => Some(decl(&["Religionen"], &[Some("Messias"), None], &[3u8, 0u8])),
        8u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Menschliches", "Grundstrukturen"], &[Some("Wichtigste"), Some("Liebe"), Some("Liebe_(7)"), None], &[0u8, 5u8])),
        9u32 => Some(decl(&["Menschliches", "Grundstrukturen"], &[Some("Liebe"), Some("Liebe_(7)"), None], &[0u8, 5u8])),
        10u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Grundstrukturen", "Menschliches"], &[Some("Wichtigste"), Some("Paradigmen_sind_Absichten_(13)"), Some("Motive"), None], &[3u8, 0u8])),
        11u32 => Some(decl(&["Menschliches"], &[Some("Errungenschaften"), None], &[3u8, 0u8])),
        12u32 => Some(decl(&["Menschliches"], &[Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), None], &[3u8, 0u8])),
        13u32 => Some(decl(&["Menschliches", "Menschliches"], &[Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), Some("brauchen"), None], &[3u8, 0u8])),
        14u32 => Some(decl(&["Menschliches"], &[Some("brauchen"), None], &[3u8, 0u8])),
        15u32 => Some(decl(&["Pro_Contra"], &[Some("contra"), None], &[3u8, 4u8, 0u8, 5u8])),
        16u32 => Some(decl(&["Religionen"], &[Some("gleichförmiges_Polygon"), None], &[3u8, 1u8])),
        17u32 => Some(decl(&["Pro_Contra"], &[Some("Pro"), None], &[3u8, 4u8, 0u8, 5u8])),
        18u32 => Some(decl(&["Menschliches"], &[Some("Motive"), None], &[3u8, 0u8])),
        19u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Bedeutung"], &[Some("Zweitwichtigste"), Some("Primzahlen"), None], &[3u8, 0u8])),
        20u32 => Some(decl(&["Größenordnung", "Licht"], &[Some("Licht"), None, None], &[3u8, 4u8, 0u8, 5u8])),
        21u32 => Some(decl(&["Grundstrukturen", "Größenordnung"], &[Some("Strukturgrösse"), Some("Strukturgrösse"), None], &[3u8, 4u8, 0u8, 5u8])),
        22u32 => Some(decl(&["Bedeutung"], &[Some("Anwendung_der_Sonnen_und_Monde"), None], &[3u8, 0u8])),
        23u32 => Some(decl(&["Religionen"], &[Some("Vertreter_höherer_Konzepte"), None], &[3u8, 0u8])),
        24u32 => Some(decl(&["Grundstrukturen", "Menschliches"], &[Some("gegen_5"), Some("Krankheit"), None], &[3u8, 0u8])),
        25u32 => Some(decl(&["Universum", "Bedeutung", "Kontinuum"], &[Some("Netzwerk"), Some("Zählungen"), Some("X"), None], &[4u8, 0u8])),
        26u32 => Some(decl(&["Pro_Contra"], &[Some("contra"), None], &[3u8, 4u8, 0u8, 5u8])),
        27u32 => Some(decl(&["Größenordnung", "Menschliches", "Licht"], &[Some("Licht"), Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), None, None], &[4u8, 0u8])),
        28u32 => Some(decl(&["Menschliches", "Grundstrukturen"], &[Some("Liebe"), Some("Liebe_(7)"), None], &[0u8, 5u8])),
        29u32 => Some(decl(&["Grundstrukturen", "Menschliches"], &[Some("Gefühle_(7)"), Some("Anführer"), None], &[3u8, 0u8])),
        30u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Größenordnung", "Menschliches"], &[Some("Zweitwichtigste"), Some("Organisationen"), Some("Berufe"), None], &[3u8, 0u8])),
        31u32 => Some(decl(&["Menschliches"], &[Some("Lösungen"), None], &[3u8, 0u8])),
        32u32 => Some(decl(&["Menschliches"], &[Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), None], &[3u8, 0u8])),
        33u32 => Some(decl(&["Grundstrukturen", "Menschliches"], &[Some("Stimmungen_Kombinationen_(14)"), Some("Musik"), None], &[3u8, 0u8])),
        34u32 => Some(decl(&["Universum", "Bedeutung"], &[Some("universelles_Recht"), Some("Jura"), None], &[3u8, 0u8])),
        35u32 => Some(decl(&["Bedeutung"], &[Some("Vollkommenheit_des_Geistes"), None], &[3u8, 0u8])),
        36u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Religionen", "Religionen", "Symbole"], &[Some("Wichtigste"), Some("Sternpolygon"), Some("der_Tierkreiszeichen"), Some("Religionen"), None], &[3u8, 4u8, 0u8, 5u8])),
        37u32 => Some(decl(&["Wichtigstes_zum_gedanklich_einordnen", "Religionen", "Symbole"], &[Some("Wichtigste"), Some("gleichförmiges_Polygon"), Some("Religionen"), None], &[3u8, 5u8, 1u8, 4u8])),
        42u32 => Some(decl(&["Grundstrukturen", "Grundstrukturen", "Menschliches"], &[Some("Reziprokes"), Some("Paradigmen_sind_Absichten_(13)"), Some("Motive"), None], &[3u8, 1u8])),
        43u32 => Some(decl(&["Inkrementieren"], &[None, None], &[3u8, 0u8])),
        45u32 => Some(decl(&["Bedeutung"], &[Some("Zählungen"), None], &[3u8, 0u8])),
        46u32 => Some(decl(&["Menschliches"], &[Some("alpha_beta"), None], &[3u8, 0u8])),
        47u32 => Some(decl(&["Menschliches"], &[Some("evolutionär_erwerben_und_Intelligenz_Kreativität"), None], &[3u8, 0u8])),
        48u32 => Some(decl(&["Pro_Contra"], &[Some("Pro"), None], &[3u8, 4u8, 0u8, 5u8])),
        51u32 => Some(decl(&["Menschliches"], &[Some("dominierendes_Geschlecht"), None], &[3u8, 0u8])),
        52u32 => Some(decl(&["Eigenschaften_n"], &[Some("gut_böse_lieb_schlecht"), None], &[3u8, 1u8, 0u8])),
        53u32 => Some(decl(&["Eigenschaften_n"], &[Some("gut_böse_lieb_schlecht"), None], &[3u8, 1u8, 0u8])),
        54u32 => Some(decl(&["Grundstrukturen", "Größenordnung", "Universum", "Universum", "Inkrementieren", "Inkrementieren"], &[Some("Strukturgrösse"), Some("Strukturgrösse"), Some("Transzendentalien"), Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), None, Some("warum_Transzendentalie_=_Strukturgroesse_=_Charakter"), None], &[3u8, 4u8, 0u8])),
        55u32 => Some(decl(&["Universum", "Universum", "Kontinuum"], &[Some("Transzendentalien"), Some("Netzwerk"), Some("X"), None], &[4u8, 0u8])),
        57u32 => Some(decl(&["Menschliches"], &[Some("Angreifbarkeit"), None], &[3u8, 0u8])),
        58u32 => Some(decl(&["Menschliches"], &[Some("Angreifbarkeit"), None], &[3u8, 1u8])),
        59u32 => Some(decl(&["Menschliches"], &[Some("Glaube_Erkenntnis"), None], &[3u8, 0u8])),
        64u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Bedeutung"], &[Some("Drittwichtigste"), Some("Gestirn"), None], &[3u8, 0u8])),
        65u32 => Some(decl(&["Wichtigstes_zum_verstehen", "Universum", "Universum", "Grundstrukturen", "Universum", "Multiversum", "Inkrementieren"], &[Some("Zweitwichtigste"), Some("universelles_Recht"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("warum_Transzendentalie_=_Komplexität_von_Michael_Commons"), None], &[4u8, 0u8])),
        68u32 => Some(decl(&["Menschliches"], &[Some("INCELs"), None], &[3u8, 0u8])),
        69u32 => Some(decl(&["Grundstrukturen", "Wirtschaft"], &[Some("System"), Some("System"), None], &[4u8, 0u8])),
        70u32 => Some(decl(&["Grundstrukturen", "Wirtschaft"], &[Some("System"), Some("System"), None], &[4u8, 0u8])),
        71u32 => Some(decl(&["Wirtschaft"], &[Some("Erklärung"), None], &[3u8, 0u8])),
        72u32 => Some(decl(&["Religionen"], &[Some("Religions-Gründer-Typ"), None], &[3u8, 0u8])),
        73u32 => Some(decl(&["Menschliches"], &[Some("irrationale_Zahlen_durch_Wurzelbildung"), None], &[3u8, 0u8])),
        74u32 => Some(decl(&["Inkrementieren"], &[None, None], &[3u8, 0u8])),
        75u32 => Some(decl(&["Grundstrukturen", "Universum", "Multiversum"], &[Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), Some("Model_of_Hierarchical_Complexity"), None], &[3u8, 4u8, 0u8])),
        76u32 => Some(decl(&["Operationen"], &[Some("4"), None], &[3u8, 4u8, 0u8])),
        77u32 => Some(decl(&["Universum", "Galaxie", "Operationen"], &[Some("Kugeln_Kreise"), Some("Kugeln_Kreise"), Some("4"), None], &[4u8, 0u8])),
        78u32 => Some(decl(&["Operationen"], &[Some("2"), None], &[3u8, 0u8])),
        79u32 => Some(decl(&["Planet_(10_und_oder_12)", "Planet_(10_und_oder_12)", "Operationen", "Grundstrukturen"], &[Some("Meta-Systeme_(12)"), Some("Gleichheit_Freiheit_Ordnung"), Some("2"), Some("Meta-Systeme_(12)"), None], &[3u8, 0u8])),
        80u32 => Some(decl(&["Planet_(10_und_oder_12)", "Planet_(10_und_oder_12)", "Operationen", "Grundstrukturen"], &[Some("Meta-Systeme_(12)"), Some("Gleichheit_Freiheit_Ordnung"), Some("2"), Some("Meta-Systeme_(12)"), None], &[4u8, 0u8])),
        81u32 => Some(decl(&["Operationen"], &[Some("4"), None], &[4u8, 0u8])),
        82u32 => Some(decl(&["Größenordnung"], &[Some("Organisationen"), None], &[3u8, 0u8])),
        83u32 => Some(decl(&["Größenordnung"], &[Some("politische_Systeme"), None], &[3u8, 0u8])),
        84u32 => Some(decl(&["Grundstrukturen", "Galaxie", "Universum"], &[Some("analytische_Ontologie"), Some("analytische_Ontologie"), Some("analytische_Ontologie"), None], &[4u8, 0u8])),
        86u32 => Some(decl(&["Operationen"], &[Some("Halbierung"), None], &[3u8, 0u8])),
        87u32 => Some(decl(&["Religionen"], &[Some("Sternpolygon_vs_gleichförmiges"), None], &[3u8, 1u8, 0u8])),
        88u32 => Some(decl(&["Menschliches", "Eigenschaften_n"], &[Some("Sinn_des_Lebens"), Some("Sinn_und_Zweck_des_Lebens"), None], &[3u8, 0u8])),
        89u32 => Some(decl(&["Wirtschaft"], &[Some("Maschinen"), None], &[3u8, 0u8])),
        90u32 => Some(decl(&["Galaxie"], &[Some("Offenbarung_des_Johannes"), None], &[3u8, 0u8])),
        91u32 => Some(decl(&["Galaxie"], &[Some("chinesisches_Horoskop"), None], &[3u8, 0u8])),
        92u32 => Some(decl(&["Operationen"], &[Some("3"), None], &[3u8, 0u8])),
        93u32 => Some(decl(&["Operationen"], &[Some("3"), None], &[4u8, 0u8])),
        94u32 => Some(decl(&["Operationen"], &[Some("9"), None], &[4u8, 0u8])),
        95u32 => Some(decl(&["Inkrementieren"], &[None, None], &[3u8, 0u8])),
        96u32 => Some(decl(&["Operationen"], &[Some("5"), None], &[3u8, 0u8])),
        99u32 => Some(decl(&["Wirtschaft"], &[Some("Organisationsform"), None], &[3u8, 0u8])),
        100u32 => Some(decl(&["Pro_Contra"], &[Some("Gegenteil"), None], &[3u8, 4u8, 0u8, 5u8])),
        101u32 => Some(decl(&["Pro_Contra"], &[Some("Gegenteil"), None], &[3u8, 4u8, 0u8, 5u8])),
        102u32 => Some(decl(&["Pro_Contra"], &[Some("Harmonie"), None], &[3u8, 4u8, 0u8, 5u8])),
        103u32 => Some(decl(&["Pro_Contra"], &[Some("Harmonie"), None], &[3u8, 4u8, 0u8, 5u8])),
        104u32 => Some(decl(&["Operationen"], &[Some("4"), None], &[4u8, 0u8])),
        105u32 => Some(decl(&["Menschliches"], &[Some("Gefühle"), None], &[3u8, 0u8])),
        106u32 => Some(decl(&["Bedeutung"], &[Some("Konjunktiv_Wurzelbildung"), None], &[3u8, 0u8])),
        107u32 => Some(decl(&["Planet_(10_und_oder_12)", "Bedeutung"], &[Some("Mechanismen"), Some("Mechanismen_der_Züchtung"), None], &[4u8, 0u8, 5u8])),
        108u32 => Some(decl(&["Bedeutung"], &[Some("Mechanismen_der_Züchtung"), None], &[3u8, 0u8])),
        109u32 => Some(decl(&["Wirtschaft", "Bedeutung"], &[Some("BWL"), Some("Mechanismen_der_Züchtung"), None], &[3u8, 0u8])),
        112u32 => Some(decl(&["Eigenschaften_n"], &[Some("Weisheit_etc"), None], &[3u8, 0u8])),
        113u32 => Some(decl(&["Wirtschaft"], &[Some("Pflanzen"), None], &[3u8, 0u8])),
        114u32 => Some(decl(&["Pro_Contra"], &[Some("Hilfe_erhalten"), None], &[3u8, 4u8, 0u8, 5u8])),
        115u32 => Some(decl(&["Pro_Contra"], &[Some("Helfen"), None], &[3u8, 4u8, 0u8, 5u8])),
        116u32 => Some(decl(&["Pro_Contra"], &[Some("Gegenposition"), None], &[3u8, 4u8, 0u8, 5u8])),
        117u32 => Some(decl(&["Pro_Contra"], &[Some("pro_nutzen"), None], &[3u8, 4u8, 0u8, 5u8])),
        118u32 => Some(decl(&["Bedeutung"], &[Some("Vorzeichen"), None], &[3u8, 0u8])),
        119u32 => Some(decl(&["Bedeutung"], &[Some("Vorzeichen"), None], &[3u8, 0u8])),
        120u32 => Some(decl(&["Pro_Contra"], &[Some("nervig"), None], &[3u8, 4u8, 0u8, 5u8])),
        123u32 => Some(decl(&["Pro_Contra"], &[Some("nicht_miteinander_auskommen"), None], &[3u8, 4u8, 0u8, 5u8])),
        124u32 => Some(decl(&["Pro_Contra"], &[Some("nicht_dagegen"), None], &[3u8, 4u8, 0u8, 5u8])),
        125u32 => Some(decl(&["Pro_Contra"], &[Some("kein_Gegenteil"), None], &[3u8, 4u8, 0u8, 5u8])),
        126u32 => Some(decl(&["Pro_Contra"], &[Some("nicht_dafür"), None], &[3u8, 4u8, 0u8, 5u8])),
        127u32 => Some(decl(&["Pro_Contra"], &[Some("Hilfe_nicht_gebrauchen"), None], &[3u8, 4u8, 0u8, 5u8])),
        128u32 => Some(decl(&["Pro_Contra"], &[Some("nicht_helfen_können"), None], &[3u8, 4u8, 0u8, 5u8])),
        129u32 => Some(decl(&["Pro_Contra"], &[Some("nicht_abgeneigt"), None], &[3u8, 4u8, 0u8, 5u8])),
        130u32 => Some(decl(&["Pro_Contra"], &[Some("unmotivierbar"), None], &[3u8, 4u8, 0u8, 5u8])),
        131u32 => Some(decl(&["Universum", "Grundstrukturen", "Multiversum", "Grundstrukturen"], &[Some("Reziproke_von_Transzendentalien"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("Strukturalien_bzw_Meta-Paradigmen_bzw_Transzendentalien_(15)"), Some("Reziprokes"), None], &[4u8, 1u8])),
        132u32 => Some(decl(&["Planet_(10_und_oder_12)", "Menschliches", "Grundstrukturen"], &[Some("Gleichheit_Freiheit_Ordnung"), Some("Gleichheit_Freiheit"), Some("Ordnung_und_Filterung_12_und_1pro12"), None], &[4u8, 0u8, 5u8])),
        135u32 => Some(decl(&["Menschliches"], &[Some("Wirkung"), None], &[3u8, 4u8, 0u8])),
        136u32 => Some(decl(&["Menschliches", "Eigenschaften_n"], &[Some("Egoismus"), Some("Egoismus_vs_Altruismus"), None], &[3u8, 0u8])),
        137u32 => Some(decl(&["Pro_Contra"], &[Some("Gegenspieler"), None], &[3u8, 4u8, 0u8, 5u8])),
        138u32 => Some(decl(&["Universum", "Menschliches"], &[Some("Gegentranszendentalien"), Some("Gegentranszendentalien"), None], &[4u8, 0u8])),
        139u32 => Some(decl(&["Menschliches"], &[Some("Gegentranszendentalien"), None], &[3u8, 0u8])),
        140u32 => Some(decl(&["Pro_Contra"], &[Some("ergibt_Sinn"), None], &[3u8, 4u8, 0u8, 5u8])),
        241u32 => Some(decl(&["Menschliches", "Grundstrukturen"], &[Some("Gesellschaftsschicht"), Some("Klassen_(20)"), None], &[3u8, 0u8, 5u8])),
        242u32 => Some(decl(&["Universum", "Grundstrukturen", "Grundstrukturen", "Multiversum"], &[Some("Geist__(15)"), Some("nachvollziehen_emotional_oder_geistig_durch_Primzahl-Kreuz-Algorithmus_(15)"), Some("Geist_(15)"), Some("Geist_(15)"), None], &[4u8, 0u8])),
        243u32 => Some(decl(&["Menschliches", "Grundstrukturen"], &[Some("Gefühle"), Some("Gefühle_(7)"), None], &[0u8, 5u8])),
        249u32 => Some(decl(&["Grundstrukturen", "Menschliches"], &[Some("Gedanken_sind_Positionen_(17)"), Some("Gedanken_sind_Positionen_(17)"), None], &[0u8, 5u8])),
        303u32 => Some(decl(&["Galaxie"], &[Some("Thomasevangelium"), None], &[3u8, 0u8])),
        314u32 => Some(decl(&["Menschliches"], &[Some("Mensch-zu-Tier"), None], &[4u8, 0u8, 5u8])),
        324u32 => Some(decl(&["Planet_(10_und_oder_12)"], &[Some("Gleichheit_Freiheit_Ordnung"), None], &[0u8, 5u8])),
        466u32 => Some(decl(&["Menschliches", "Grundstrukturen"], &[Some("Gewalt"), Some("Gewalt"), None], &[3u8, 4u8, 0u8])),
        _ => None,
    }
}

pub fn all_typed_exact_decls() -> Vec<(u32, HtmlDeclMeta)> {
    TYPED_EXACT_DECL_COLUMNS
        .iter()
        .filter_map(|&col| typed_exact_decl_for_column(col).map(|meta| (col, meta)))
        .collect()
}