[package]
name = "retaprompt_input"
version = "0.7.0"
edition = "2024"
autobins = false
publish = false

[lib]
name = "retaprompt_input"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
reta_architecture = { path = "../reta_architecture" }
indexmap = { version = "2", features = ["serde"] }
retaprompt_commands = { path = "../retaprompt_commands" }
reedline = "0.47.0"
ratatui = { version = "0.30.0", features = ["crossterm"] }
crossterm = "0.29.0"

#[[bin]]
#name = "retaprompt_completion_probe"
#path = "src/bin/retaprompt_completion_probe.rs"
