#!/bin/sh
SCRIPT_PATH="${BASH_SOURCE:-$0}"
ABS_SCRIPT_PATH="$(realpath "${SCRIPT_PATH}")"
ABS_DIRECTORY="$(dirname "${ABS_SCRIPT_PATH}")"
GIT_DIRECTORY="${ABS_DIRECTORY}/.git"

#cd ~/myRepos/reta
echo "Value of ABS_DIRECTORY: ${GIT_DIRECTORY}"
echo aktueller Branch: `git --git-dir ${GIT_DIRECTORY} branch | grep '*' | awk '{print $2}'`
echo In den Feature Branch wechseln oder Master ? m für master und f für feature, alles andere wechselt zum Master Branch !!!!!!
echo Es wird empfohlen Programmierungen im Feature-Branch durchzuführen und csvs input im master branch
read branchwechslung
[ "$branchwechslung" = "m" ] && git --git-dir ${GIT_DIRECTORY} --work-tree=${ABS_DIRECTORY} switch master
[ "$branchwechslung" = "f" ] && git --git-dir ${GIT_DIRECTORY} --work-tree=${ABS_DIRECTORY} switch feature || git --git-dir ${GIT_DIRECTORY} --work-tree=${ABS_DIRECTORY} switch master
sleep 2
file=`ls ${ABS_DIRECTORY}/csv -S | grep -e '\.csv$' | fzf`
if [ "$file" != "" ];then
    libreoffice ${ABS_DIRECTORY}/csv/${file}
fi
