#!/bin/bash
./reta -spalten --alles --breite=0 -ausgabe --art=html --onetable --nocolor > middle.alx
    cat head1.alx
    cat religionen.js
    cat head2.alx
    cat middle.alx
    ./grundStrukHtml.py blank
    cat footer.alx
