// AUTO-GENERATED from reta.todel/i18n/words.py
pub const META_KONKRET_MAPPINGS: &[(&[&str], (usize, usize))] = &[
    (&["meta"], (2, 0)),
    (&["konkret"], (2, 1)),
    (&["Theorie", "theorie"], (3, 0)),
    (&["Praxis", "praxis"], (3, 1)),
    (&["Management", "management", "stau"], (4, 0)),
    (&["verändernd", "veraendernd", "fluss"], (4, 1)),
    (&["ganzheitlich", "mathematisch_diskret", "diskret"], (5, 0)),
    (&["darüber_hinausgehend", "hinausgehend", "kontinuierlich"], (5, 1)),
    (&["Unternehmung_Geschäft", "unternehmen", "unternehmung", "geschaeft", "geschäft"], (6, 0)),
    (&["wertvoll", "wert"], (6, 1)),
    (&["Beherrschen", "regieren", "beherrschen"], (7, 0)),
    (&["Richtung", "richtung", "gut"], (7, 1)),
];

pub const EIGENSCHAFT_MAPPINGS: &[(&[&str], &[usize], Option<(usize, usize)>)] = &[
    (&["Weisheit_etc", "weisheit", "metaweisheit", "meta-weisheit", "idiot", "weise", "optimal", "optimum"], &[112], Some((40, 41))),
    (&["Dein_Recht_bekommen", "rechte", "recht", "selbstgerecht"], &[], Some((291, 292))),
    (&["unterlegen_überlegen", "unterlegen", "ueberlegen"], &[], Some((380, 381))),
    (&["Ehrlichkeit_und_Streit", "streit", "ehrlichkeit"], &[], Some((375, 376))),
    (&["einklinken_vertrauen_anprangern", "einklinken", "vertrauenerhalten", "anprangern"], &[], Some((368, 369))),
    (&["familiebrauchen"], &[], Some((279, 280))),
    (&["ego", "bescheiden"], &[], Some((277, 278))),
    (&["Selbstsucht_Ichsucht_etc", "selbstsucht", "ichsucht"], &[], Some((274, 275))),
    (&["Forschen_Erfinden_Einklinken", "wissenschaft", "forschen", "einklinken", "erfinden"], &[], Some((258, 259))),
    (&["Kooperation_vs_Arsch", "arschloch", "kooperation", "arsch"], &[], Some((245, 246))),
    (&["Liebe_usw", "liebe", "zuneigung"], &[], Some((247, 248))),
    (&["Selbstlosigkeit_Ichlosigkeit_etc", "selbstlos", "ichlos"], &[], Some((238, 239))),
    (&["variationsreich_eintönig", "eintönig", "eintoenig", "variationsreich"], &[], Some((236, 237))),
    (&["Zuneigung_Abneigung", "abgeneigt", "zugewandt", "reserviert", "zugeneigt"], &[], Some((199, 200))),
    (&["delegieren", "ansammlung"], &[], Some((227, 228))),
    (&["ehrlich_vs_höflich", "ehrlich", "höflich", "hoeflich"], &[], Some((224, 225))),
    (&["Tragweite", "tragweite"], &[], Some((211, 212))),
    (&["wertvoll", "wertlos"], &[], Some((186, 187))),
    (&["Götter_Propheten_Familien_Freunde", "familiaer", "goettlich", "freunde", "propheten"], &[], Some((184, 185))),
    (&["sanft_vs_hart", "sanft", "hart"], &[], None),
    (&["vereinen_vs_verbinden", "vereinenverbinden", "vereinen", "verbinden", "einheit", "verbindung"], &[], Some((133, 134))),
    (&["ähnlich", "aehnlich"], &[220], None),
    (&["gut_böse_lieb_schlecht", "gut", "böse", "boese", "lieb", "schlecht"], &[52, 53], Some((38, 39))),
    (&["Sinn_und_Zweck_des_Lebens", "sinn", "zweck", "bedeutung"], &[88, 189], Some((181, 182))),
    (&["Zeit_vs_Raum", "zeit", "raum", "zeitlich", "räumlich"], &[], Some((49, 50))),
    (&["egalitär_vs_autoritär", "egalitaerautoritaer", "egalitaer", "autoritaer", "egalitär", "autoritär"], &[], Some((163, 164))),
    (&["Meinungen_und_Ruf", "meinungen", "anderemenschen", "ruf"], &[], Some((60, 61))),
    (&["Meinungsintelligenz", "meinungsintelligenz", "ursprungsintelligenz"], &[], Some((151, 152))),
    (&["Sittlichkeit", "sittlichkeit", "annaehrerung"], &[], Some((179, 180))),
    (&["Führung", "führung", "fuehrung"], &[], Some((173, 174))),
    (&["Durchleuchten", "durchleuchten", "erleuchten"], &[], Some((177, 178))),
    (&["Fördern_Sensiblisieren_und_Gedeihen", "foerdern", "fördern", "begrenzen", "sensibilisieren", "gedeihen", "verderben"], &[], Some((175, 176))),
    (&["Überheblichkeit", "überheblich", "ueberheblichkeit", "ueberheblich", "überheblichkeit"], &[], Some((171, 172))),
    (&["Polung_der_Liebe", "liebepolung"], &[], Some((121, 122))),
    (&["Egoismus_vs_Altruismus", "egoismus", "altruismus", "egoist", "altruist"], &[136], Some((66, 67))),
    (&["kausal", "geltung", "genese"], &[], Some((110, 111))),
    (&["Gleichheit", "gleich"], &[], Some((192, 193))),
    (&["Überleben", "ueberleben"], &[], Some((194, 195))),
    (&["Würdig", "wuerdig", "würdig"], &[], Some((373, 374))),
    (&["Regel_vs_Ausnahme", "regel", "ausnahme"], &[], Some((371, 372))),
    (&["Filterart_Widrigkeit", "filterart", "widrigkeit"], &[331, 335], None),
    (&["Werte", "werte"], &[], Some((360, 361))),
    (&["Gutartigkeits-Egoismus", "position", "gutesreziprok"], &[], Some((362, 363))),
    (&["Reflektieren_Erkenntnis-Erkennen", "reflektieren", "erkenntnis"], &[], Some((364, 365))),
    (&["Vertrauen_wollen", "vertrauenwollen"], &[], Some((366, 367))),
    (&["Ausrichten_Einrichten", "einrichten", "ausrichten"], &[], Some((358, 359))),
    (&["Toleranz_Respekt_Akzeptanz_Willkommen", "toleranz", "respekt", "akzeptanz", "willkommen"], &[], Some((359, 360))),
];
